---
title: "qs@talks"
author: "Dario Riccardo Valenzano"
date: "2023-08-23"
output:
  html_document:
    css: style.css
  pdf_document: default
---

## Asking questions after a seminar - a practical guide 

In this document I share some thoughts about the "art of asking scientific questions".[^1]  
My goal is to share with you a rudimentary toolbox to work your way into asking questions more frequently and more effectively. 

[^1]: What this document is NOT about, is the etiquette of asking questions. I am not thinking about how to ask questions politely or professionally. Rather, I am sharing thoughts about how to come up with a list of reasonable questions and what they could be about.

Asking questions after a scientific presentation is very important. It is part of the dialectic of science. Questioning and discussing experiments, methods, results and interpretations is what makes science fun and so effective. Ideas bounce, conclusions are challenged, a new model emerges from the discussion. As scientists, we ought to question stuff. 

After I give a talk, if nobody asks a question, I feel I did not do my job well. If I invite a guest speaker and after the seminar nobody in the hosting institute asks a question, I feel I am letting down both the guest and the audience. No questions asked is a symptom that presenter and audience are out of sync.

Let's start from the basics. Why would I ask questions at all?  

Here are a few realistic reasons:

1. I am genuinely curious to know more about what was presented.
2. I am confused about the methods or results presented. I need more info to fully appreciate the method or the results presented.
3. While I get the results, I am not convinced about the interpretation.
4. I am shocked - I can't believe what I heard was true or even possible. I need to make sure I understood correctly.
5. This is cool work. In the context of what I heard, I wonder what the presenter thinks about other recently published results.
6. Gosh, my PI wants me to ask questions and I feel I have to show I paid attention.
7. My colleagues asks so many questions - I should do the same!
8. (...).

I found useful to think "asking questions" as a specific task, which I set even before the talk starts.  
Let me clarify. I sometimes explicitly decide before a talk that I will have 2-3 questions written down ready to be asked (it's OK if I do not get to ask them). I sometimes write "2" and I circle it at the top of my notebook page. That number will indicate the number of questions I set myself to have at the end of the presentation.   Whenever I moderate a session at a conference, I host an invited speaker, or I am invited to a conference, I need to have questions to stimulate the discussion and actively contribute to the scientific debate. If I am in the "I really should ask a question after this talk" mode, I will avidly take notes and write down a question as soon as something comes up during the talk. If I listen to someone's presentation with this "asking question" mindset, I find it much easier to come up at the end with questions, as opposed to casually thinking about possible questions only at the end of a talk. In other words, asking question can be exercised, and I believe it is an important part of our scientific training. You can definitely practice and learn to ask questions. 

## Scenario 1. What question should I ask?
This seems to be a tough one.  
As you know well by now, each talk has a rather standard structure, with only a few limited accepted variations. It starts with a title slide, then continues with the background information, the gap in knowledge, the main research question, the approach/methods, the results, the interpretation of the results, the discussion of the results in the broad context of the field, the conclusions, the future directions (sometimes), and the acknowledgments of the people, institutions and funding bodies that contributed to the project.  
The great news is that you can ask questions that relate to pretty much all the components of the presentation, starting from the title, all the way to the acknowledgments.    
Here are a few examples:  
_Background_: do I agree with the provided information? Is there something that was missed that would have led to a different formulation of the question? Did I know about the background that was provided? Can the author tell more about the background information? What if some info provided as a background was recently refuted/challenged? We should ask for the presenter's opinion.    
_Methods_: Do I understand the methods? Can the authors explain how the methods work in some more detail? I am not sure I am following. How can one go from a to b? What is 16S rRNA Sequencing? How does the pipeline work? How do you correct for batch effect? Were the experiments done at the same time of the day? Were experiments done both in male and female mice? Why did the authors use killifish instead of zebrafish?    
_Results_: This is exciting. However, I am not sure I understand that plot. What is shown on the x axis? What is on the y axis? What does the legend indicate? What is a t-SNE plot? Did I see gene A appearing on that list? Can you tell me more about it? Did you check which paralog was that? What does that gene do?  
_Interpretation_: While I see that the interpretation presented is plausible, can an alternative scenario also explain the observed results? How can the presenter choose one interpretation over the other? Shall they rather test for a, b, and c, in order to be sure they got the mechanism/structure right? Are there additional interpretations for the presented results? This is the place to ask yourself (and perhaps the presenter) whether the title reflects the presented results. If it does not (sometimes that's the case), for example you can ask: you titled your talk "Evolutionary Ecology of Aging", but then you talked about demography and genomics. Did I miss the part about ecology?  
_Discussion_: This is the place where the results are discussed in the context of what is already known, and where the true novelty/relevance of the results is discussed. Often, the discussion of each result occurs in the same slide where results are shown. This is the place to compare the presented results with something that is already known, that was already published, or perhaps with some personal observation/finding. Here you can ask "If what you showed is true, does it then mean that a, b, c, are also possible/true/false?"  
_Future directions_: even here we can ask questions: can the presenter consider doing additional experiments? Should the presenter perhaps check dataset a, b, c, to further test their model? Is the shown mechanism evolutionary conserved (rather frequent, generic, and evergreen question)? Did the authors know whether gene A is associated with any known human disease (another classic)?  
_Acknowledgments_: you can ask whether funding agency X, which shows in your acknowledgment page, still funds projects related to the topic presented.  

As you see, you can ask questions that address virtually each part of the presentation. That's cool, there's plenty of room for questions. 

### Scenario 2. I have questions - but I am afraid to raise my hand and ask them.
One thing is to have a question in mind. Another one is to formulate and voice the question though. 
I mean, I think I do have a question, but I am wondering whether I am formulating it well enough. 
My suggestion here is to write down the question. Reading the question is perfectly fine.  
What if I am afraid to speak up? A trick that works for me to mitigate the social anxiety of being in a crowded hall with other judging heads is to sit at the front rows. In this way I can hear the presentation more clearly, I get less distracted, and being at the front I forget there is plenty of people behind me, so I am less nervous.  

### Tricks.
Here is a collection of tricks that might help you ask questions more often:

1. Plan to ask two questions before the talk starts.
2. Write down questions on your notebook as you take notes during the talk.
3. Break down the notes in introduction-methods-results-discussion and search for possible questions for each of these parts. Do this search before the talk ends - otherwise you will be distracted by other ppl questions. 
4. From time to time, throughout the talk, try to recap mentally what the presenter is telling you. Build your model of the project you heard so far. It will help you find the information that you're missing. Once you identify this missing part, you might have a question. 
5. ChatGPT (I am looking at you): if the speaker is presenting a work published as a preprint, as a proceedings abstract, or is presenting published work, you have the opportunity to submit the abstract and discussion to ChatGPT and query to formulate 3 questions. Pick one that you like and use it to practice "asking questions". This trick goes more into the mode of "practicing asking questions" rather than helping you ask your very own question. It can be fun to try.

### A final note.
Everyone asks questions in a unique way. 
If you pay attention, different people tend to ask each the same type of question, with a rather consistent formulation. Some people are more focused on the general model (big picture), other about technical details. By practicing "asking questions", you will find out what type of questions suit you best. 

